// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_src_TMBExports
#include <TMB.hpp>
#include ""

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
    Rf_error("Unknown model.");
  return 0;
}
